import { PrismaService } from '../../config/prisma.service';
import { VenuesService } from '../venues/venues.service';
import { MatchesService } from './matches.service';
import { MatchInviteService } from './match-invite.service';
import { MatchConfirmationService } from './match-confirmation.service';
import { WeeklyMatchingService } from './weekly-matching.service';

// Integration seam: the venue flow is pull-based off the Match row (see
// matches.service). This test runs the real weekly matcher and the real
// MatchesService against one shared in-memory store to prove that a match
// generated by WeeklyMatchingService is what triggers venue selection —
// without WeeklyMatchingService ever calling venue code directly.

interface StoredMatch {
  id: string;
  userAId: string;
  userBId: string;
  compatibilityScore: number;
  status: string;
}
interface StoredVenue {
  id: string;
  name: string;
  active: boolean;
  averageSpentPerPerson: number;
  tags: string[];
  [key: string]: unknown;
}
interface StoredOption {
  matchId: string;
  venueId: string;
  userAId?: string;
  userBId?: string;
  userASelected: boolean;
  userBSelected: boolean;
}

function buildUser(id: string, gender: string, interest: string) {
  return {
    id,
    isVerified: true,
    profile: {
      gender,
      dateOfBirth: new Date('2003-01-01'),
      university: 'EAFIT',
      major: 'Ingeniería',
      semester: '6',
      height: 175,
      biography: 'Me gusta viajar y la musica',
      hobbies: [{ hobby: { name: 'Cine' } }],
    },
    preferences: {
      genderInterest: interest,
      minAge: 18,
      maxAge: 30,
      sameUniversity: false,
      relationshipType: 'Seria',
      heightRange: 'Indiferente',
      energyVibe: 'Tranquila',
    },
  };
}

function makeStore() {
  const users = [
    buildUser('m', 'Masculino', 'Mujeres'),
    buildUser('w', 'Femenino', 'Hombres'),
  ];
  const matches: StoredMatch[] = [];
  const venueOptions: StoredOption[] = [];
  const venues: StoredVenue[] = [1, 2, 3].map((n) => ({
    id: `v${n}`,
    name: `Café ${n}`,
    type: 'Café',
    address: `Calle ${n}`,
    openingHours: '9-18',
    description: 'Nice',
    tags: [],
    averageSpentPerPerson: 10 * n,
    active: true,
  }));

  const prisma = {
    user: { findMany: () => Promise.resolve(users) },
    feedback: { findMany: () => Promise.resolve([]) },
    profile: {
      findUnique: ({ where }: { where: { userId: string } }) => {
        const user = users.find((u) => u.id === where.userId);
        return Promise.resolve(user ? { hobbies: user.profile.hobbies } : null);
      },
    },
    venue: {
      findMany: ({ where }: { where?: { active?: boolean } }) =>
        Promise.resolve(
          venues.filter((v) => (where?.active ? v.active : true)),
        ),
    },
    match: {
      findMany: ({
        where,
      }: {
        where?: { OR?: unknown; status?: { in?: string[] } };
      }) => {
        if (where?.OR) return Promise.resolve(matches); // prior-partners: none yet
        const statuses = where?.status?.in;
        return Promise.resolve(
          matches.filter((m) => !statuses || statuses.includes(m.status)),
        );
      },
      findFirst: ({
        where,
      }: {
        where: { OR: { userAId?: string }[]; status?: { in?: string[] } };
      }) => {
        const uid = where.OR[0].userAId;
        const statuses = where.status?.in;
        return Promise.resolve(
          matches.find(
            (m) =>
              (m.userAId === uid || m.userBId === uid) &&
              (!statuses || statuses.includes(m.status)),
          ) ?? null,
        );
      },
      createMany: ({ data }: { data: Omit<StoredMatch, 'id'>[] }) => {
        for (const row of data) {
          matches.push({ id: `match-${matches.length}`, ...row });
        }
        return Promise.resolve({ count: data.length });
      },
    },
    venueOption: {
      findMany: ({ where }: { where: { matchId: string } }) =>
        Promise.resolve(
          venueOptions
            .filter((o) => o.matchId === where.matchId)
            .map((o) => ({
              ...o,
              venue: venues.find((v) => v.id === o.venueId),
            })),
        ),
      count: () => Promise.resolve(0),
      createMany: ({
        data,
      }: {
        data: { matchId: string; venueId: string }[];
      }) => {
        for (const row of data) {
          venueOptions.push({
            userASelected: false,
            userBSelected: false,
            ...row,
          });
        }
        return Promise.resolve({ count: data.length });
      },
    },
  } as unknown as PrismaService;

  return { prisma, matches };
}

describe('weekly matching → venue selection integration', () => {
  it('generates a match that then drives venue suggestions', async () => {
    const { prisma, matches } = makeStore();
    // runWeeklyMatching is pure of notifications, so a no-op invite stub is enough.
    const invites = {
      inviteForPairs: () => Promise.resolve(),
    } as unknown as MatchInviteService;
    const weekly = new WeeklyMatchingService(prisma, invites);
    // getVenueSuggestions doesn't touch confirmation, so a no-op stub suffices.
    const confirmation = {
      tryConfirm: () => Promise.resolve('waiting'),
    } as unknown as MatchConfirmationService;
    const matchesService = new MatchesService(
      prisma,
      new VenuesService(prisma),
      confirmation,
    );

    // 1. Weekly matcher creates exactly one pending Match row.
    const created = await weekly.runWeeklyMatching();
    expect(created).toHaveLength(1);
    expect(matches[0]).toMatchObject({
      userAId: 'm',
      userBId: 'w',
      status: 'pending',
    });

    // 2. That row alone lets the existing venue flow suggest 3 places (HU-06).
    const suggestions = await matchesService.getVenueSuggestions('m');
    expect(suggestions).toHaveLength(3);
    expect(suggestions.every((s) => 'id' in s)).toBe(true);
  });
});
